name: Run tests and upload coverage

permissions:
  contents: read

on:
  push:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      test-app:
        description: 'Test this app'
        default: 'true'
        required: false

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Create src directory if it doesn't exist
        run: mkdir -p src

      - name: Create firebase credentials.json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "firebase-service-account.json"
          json: ${{ secrets.FIREBASE_CREDENTIALS }}
          dir: "src/"

      - name: Set FIREBASE_SERVICE_ACCOUNT_PATH env variable
        run: echo "FIREBASE_SERVICE_ACCOUNT_PATH=src/firebase-service-account.json" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Debug environment
        run: |
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "Installed dependencies:"
          npm list --depth=0

      - name: Run tests with coverage
        run: npx cross-env NODE_ENV=test jest --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Practica-Supervisada-UCR-2025/Backend-MS-Notifications
